#ifndef CONFIG_H
#define CONFIG_H

#define WIFI_SSID ""
#define WIFI_PASSWORD ""

#define WEATHER_STATION_ID ""
#define WEATHER_API_KEY ""

#define WEATHER_UPDATE_INTERVAL 600000
#define WEATHER_MAX_RETRY_INTERVAL 1800000

#define WIFI_CONNECT_TIMEOUT_MS 15000
#define WIFI_RETRY_INTERVAL_MS 10000
#define SETTINGS_NAMESPACE "weathercfg"
#define SETTINGS_VERSION 2
#define DEFAULT_DEVICE_NAME "weather-display"
#define SETUP_AP_SUFFIX "-Setup"

#define TIME_ZONE "GMT0BST,M3.5.0/1,M10.5.0/2"
#define NTP_SERVER_1 "pool.ntp.org"
#define NTP_SERVER_2 "time.nist.gov"

#define LOCATION_LAT 51.57
#define LOCATION_LON -0.78

#define DISPLAY_WIDTH 480
#define DISPLAY_HEIGHT 480
#define DISPLAY_PIN_CS 39
#define DISPLAY_PIN_DC -1
#define DISPLAY_PIN_RST -1
#define DISPLAY_PIN_MOSI 47
#define DISPLAY_PIN_SCK 48
#define DISPLAY_PIN_MISO -1
#define DISPLAY_PIN_BCKL 38
#define DISPLAY_PIN_DE 18
#define DISPLAY_PIN_VSYNC 17
#define DISPLAY_PIN_HSYNC 16
#define DISPLAY_PIN_PCLK 21
#define DISPLAY_PIN_R0 11
#define DISPLAY_PIN_R1 12
#define DISPLAY_PIN_R2 13
#define DISPLAY_PIN_R3 14
#define DISPLAY_PIN_R4 0
#define DISPLAY_PIN_G0 8
#define DISPLAY_PIN_G1 20
#define DISPLAY_PIN_G2 3
#define DISPLAY_PIN_G3 46
#define DISPLAY_PIN_G4 9
#define DISPLAY_PIN_G5 10
#define DISPLAY_PIN_B0 4
#define DISPLAY_PIN_B1 5
#define DISPLAY_PIN_B2 6
#define DISPLAY_PIN_B3 7
#define DISPLAY_PIN_B4 15
#define DISPLAY_HSYNC_FRONT_PORCH 10
#define DISPLAY_HSYNC_PULSE_WIDTH 8
#define DISPLAY_HSYNC_BACK_PORCH 20
#define DISPLAY_VSYNC_FRONT_PORCH 10
#define DISPLAY_VSYNC_PULSE_WIDTH 8
#define DISPLAY_VSYNC_BACK_PORCH 10

#define TOUCH_SDA 19
#define TOUCH_SCL 45
#define TOUCH_RST -1
#define TOUCH_INT -1
#define TOUCH_GT911_PRIMARY_ADDR 0x5D
#define TOUCH_GT911_FALLBACK_ADDR 0x14
#define TOUCH_SWAP_XY 0
#define TOUCH_MIRROR_X 0
#define TOUCH_MIRROR_Y 0

#endif
